//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStoreAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Blogging
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Blogging()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int BlogId { get; set; }
        public string ShortHeading { get; set; }
        public string BlogHeading { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string Author { get; set; }
        public string BlogImage { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [XmlIgnore,JsonIgnore]
        public virtual ICollection<Product> Product { get; set; }
    }
}
