//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartStatus
    {
        public int CartStatusId { get; set; }
        public string CartStatus1 { get; set; }
    }
}
