//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickStoreAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    using System.Xml.Serialization;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        
        public Product()
        {
            this.Cart = new HashSet<Cart>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Description { get; set; }
        public string ProductImage { get; set; }
        public Nullable<bool> IsFeatured { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SId { get; set; }
        public Nullable<int> BlogId { get; set; }
        public string LongDescrib { get; set; }
        [XmlIgnore, JsonIgnore]

        public virtual Blogging Blogging { get; set; }
        [XmlIgnore, JsonIgnore]
        public virtual Sorting Sorting { get; set; }
        [XmlIgnore, JsonIgnore]
        public virtual Product Product1 { get; set; }
        [XmlIgnore, JsonIgnore]
        public virtual Product Product2 { get; set; }
        [XmlIgnore, JsonIgnore]
        public virtual Product Product11 { get; set; }
        [XmlIgnore, JsonIgnore]
        public virtual Product Product3 { get; set; }
        [XmlIgnore, JsonIgnore]
        public virtual Sorting Sorting1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [XmlIgnore,JsonIgnore]
        public virtual ICollection<Cart> Cart { get; set; }
    }
}
